<?php
/**
 * About app view script
 * 
 * @package zfcol
 * @category application/views/scripts
 * @author kamil
 * @version 1.0
 * @license http://opensource.org/licenses/bsd-3-clause new BSD license
 * @copyright (c) 2012, Kamil Kantar
 *
 */
?>
<?php Zfcol_Controller_Plugin_Title::getTitle($this->translate('About this app')); ?>
<div class="box info">
    <h4><?php echo Zend_Registry::get('AppInfo')->getName(); ?></h4>
    <p>
        <?php echo Zend_Registry::get('AppInfo')->getTag() . ' ' . $this->translate('is a free software written in PHP & Zend Framework by') . ' ' . Zend_Registry::get('AppInfo')->getAuthor(); ?>.

        <?php echo $this->translate('
        You can use it as you wish as long as you do not violate its license agreement. 
        For updates, questions, bug reports and other features, please visit project\'s website at'); ?>

        <a href="<?php echo Zend_Registry::get('AppInfo')->getWebpage(); ?>"><?php echo Zend_Registry::get('AppInfo')->getWebpage(); ?></a>. 
        <?php echo $this->translate('Your installation uses the following free software with its respective versions:'); ?>
    </p>

    <ul>
        <li><a href="<?php echo Zend_Registry::get('AppInfo')->getWebpage(); ?>"><?php echo Zend_Registry::get('AppInfo')->getTag() . ' ' . $this->version['zfcol']; ?></a></li>
        <li><a href="<?php echo $this->www['php']; ?>">PHP <?php echo $this->version['php']; ?></a></li>
        <li><a href="<?php echo $this->www['zf']; ?>">Zend Framework <?php echo $this->version['zf']; ?></a></li>
        <li><a href="<?php echo $this->www['yaml']; ?>">Yaml <?php echo $this->version['yaml']; ?></a></li>
        <li><a href="<?php echo $this->www['tcpdf']; ?>">TCPDF <?php echo $this->version['tcpdf']; ?></a></li>
        <li><a href="<?php echo $this->www['simple_html_dom']; ?>">Simple HTML Dom <?php echo $this->version['simple_html_dom']; ?></a> <?php echo $this->translate('(used by CSFD parser)'); ?></li>
    </ul>
    <h5><?php echo $this->translate('License'); ?></h5>
    <p><?php echo $this->translate('This application is licensed under the new BSD which is bundled with its package in the file LICENSE.txt. You can also read the license at http://opensource.org/licenses/bsd-3-clause'); ?></p>
</div>