<?php
/**
 * View script to display login form
 * 
 * @package zfcol
 * @category application/views/scripts
 * @author kamil
 * @version 1.0
 * @license http://opensource.org/licenses/bsd-3-clause new BSD license
 * @copyright (c) 2012, Kamil Kantar
 *
 */
?>
<section class="box info">
    <h4><?php echo $this->translate('Please log in with your username / password'); ?></h4>
    <br>
    <?php
    print $this->form;
    ?>
</section>