<?php
/**
 * Preview new movie view script
 * 
 * @package zfcol
 * @category application/views/scripts
 * @author kamil
 * @version 1.0
 * @license http://opensource.org/licenses/bsd-3-clause new BSD license
 * @copyright (c) 2012, Kamil Kantar
 *
 */
?>
<hr>
<div class="bordered float-right">
    <img src="<?php echo $this->poster; ?>"/>
</div>
<?php
$this->form->setAction($this->url(array('controller' => 'movies', 'action' => 'save')));
echo $this->form;