<?php
/**
 * Movie search results view script
 * 
 * @package zfcol
 * @category application/views/scripts
 * @author kamil
 * @version 1.0
 * @license http://opensource.org/licenses/bsd-3-clause new BSD license
 * @copyright (c) 2012, Kamil Kantar
 *
 */
?>
<?php if($this->searchform) { ?>
<div class ="info box">	
    <?php print $this->searchform; ?>	
 <div id="selectedmovie">
    </div>
</div>
<?php } 