<?php
/**
 * View script to display error messages
 * 
 * @package zfcol
 * @category application/views/scripts
 * @author kamil
 * @version 1.0
 * @license http://opensource.org/licenses/bsd-3-clause new BSD license
 * @copyright (c) 2012, Kamil Kantar
 *
 */
?>
<h3><?php echo $this->translate('An error occured'); ?></h3>
<h4><?php echo $this->message ?></h4>

<?php if (isset($this->exception)) { ?>
<p>
    <b><?php echo $this->translate('What\'s hapenned: '); ?></b> <?php echo $this->exception->getMessage() ?>
</p>
<?php } ?>